### ISSUE TITLE
installation guide

### ISSUE THREAD

**Issue by merchanos** [EikeSan/ezcon-web#1]
hello you have installation guide??

**Comment by EikeSan** [comment]
I edited the readme.md with some steps to run it

**Comment by merchanos** [comment]
thanks friend

**Comment by merchanos** [comment]
user and password?

**Comment by EikeSan** [comment]
Look at this seeder. https://github.com/EikeSan/ezcon-web/blob/master/database/seeds/UsersTableSeeder.php

**Comment by lukeconsultoria** [comment]
olá Eike tenho uma dúvida ,tentei executar mais não conseguir esse comando ,troquei as portas do banco de dados,fiz toda a execução e deu erro

**Comment by lukeconsultoria** [comment]
php artisan key:generate
Create a database and put it in .env
esses dois comandos não conseguir fazer criei o banco manualmente

**Comment by EikeSan** [comment]
@lukeconsultoria Olá, pode me relatar o erro que ocorreu?
